/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface EntryPriceMathTesterInterface extends ethers.utils.Interface {
  functions: {
    "verifyUpdateEntryPrice(int256,int256,int256,int256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "verifyUpdateEntryPrice",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyUpdateEntryPrice",
    data: BytesLike
  ): Result;

  events: {};
}

export class EntryPriceMathTester extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: EntryPriceMathTesterInterface;

  functions: {
    verifyUpdateEntryPrice(
      _entryPrice: BigNumberish,
      _position: BigNumberish,
      _tradePrice: BigNumberish,
      _positionTrade: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { newEntryPrice: BigNumber; profit: BigNumber }
    >;
  };

  verifyUpdateEntryPrice(
    _entryPrice: BigNumberish,
    _position: BigNumberish,
    _tradePrice: BigNumberish,
    _positionTrade: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { newEntryPrice: BigNumber; profit: BigNumber }
  >;

  callStatic: {
    verifyUpdateEntryPrice(
      _entryPrice: BigNumberish,
      _position: BigNumberish,
      _tradePrice: BigNumberish,
      _positionTrade: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { newEntryPrice: BigNumber; profit: BigNumber }
    >;
  };

  filters: {};

  estimateGas: {
    verifyUpdateEntryPrice(
      _entryPrice: BigNumberish,
      _position: BigNumberish,
      _tradePrice: BigNumberish,
      _positionTrade: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    verifyUpdateEntryPrice(
      _entryPrice: BigNumberish,
      _position: BigNumberish,
      _tradePrice: BigNumberish,
      _positionTrade: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
