/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MathTesterInterface extends ethers.utils.Interface {
  functions: {
    "testAddDelta(uint256,int256)": FunctionFragment;
    "testExp(int256)": FunctionFragment;
    "testLog(uint256)": FunctionFragment;
    "testMulDiv(int256,int256,int256,bool)": FunctionFragment;
    "testScale(uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "testAddDelta",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testExp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testLog",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testMulDiv",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "testScale",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "testAddDelta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "testExp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "testLog", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "testMulDiv", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "testScale", data: BytesLike): Result;

  events: {};
}

export class MathTester extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MathTesterInterface;

  functions: {
    testAddDelta(
      _x: BigNumberish,
      _y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    testExp(_x: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    testLog(_x: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    testMulDiv(
      _x: BigNumberish,
      _y: BigNumberish,
      _d: BigNumberish,
      _roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    testScale(
      _a: BigNumberish,
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  testAddDelta(
    _x: BigNumberish,
    _y: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  testExp(_x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  testLog(_x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  testMulDiv(
    _x: BigNumberish,
    _y: BigNumberish,
    _d: BigNumberish,
    _roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  testScale(
    _a: BigNumberish,
    _from: BigNumberish,
    _to: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    testAddDelta(
      _x: BigNumberish,
      _y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testExp(_x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    testLog(_x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    testMulDiv(
      _x: BigNumberish,
      _y: BigNumberish,
      _d: BigNumberish,
      _roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testScale(
      _a: BigNumberish,
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    testAddDelta(
      _x: BigNumberish,
      _y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testExp(_x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    testLog(_x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    testMulDiv(
      _x: BigNumberish,
      _y: BigNumberish,
      _d: BigNumberish,
      _roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testScale(
      _a: BigNumberish,
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    testAddDelta(
      _x: BigNumberish,
      _y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testExp(
      _x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testLog(
      _x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testMulDiv(
      _x: BigNumberish,
      _y: BigNumberish,
      _d: BigNumberish,
      _roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testScale(
      _a: BigNumberish,
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
